#%RAML 1.0 Trait
queryParameters:
  cityName:
    description: To fetch weather forecast based on city name
    type: string
  mode:
    description: To fetch weather forecast based on mode
    type: string
  date:
    description: To fetch weather forecast based on date
    type: string
  
