#%RAML 1.0 Trait
queryParameters:
  lat:
    description: To fetch weather data based on geography
    type: integer
  lon:
    description: To fetch weather data based on geography
    type: integer
